#!/usr/bin/env bash
# genUKB.exclude.sh — Build the NGS-PCA WES exclusion BED for UK Biobank (GRCh38).
#
# This script extends the standard WGS exclusion BED (GRCh38) by additionally
# masking a 20 kb buffer around the xgen exome capture targets, producing a
# combined exclusion file suitable for WES-based NGS-PCA runs.
#
# Prerequisites (must be on PATH):
#   zcat, awk, bgzip, tabix, bedtools
#
# Required input files:
#   xgen_plus_spikein.b38.bed
#       — UKB xgen exome capture BED (source: UK Biobank field 3801)
#       — wget "http://biobank.ndph.ox.ac.uk/showcase/refer.cgi?id=3801"
#   ../ngs_pca_exclude.sv_blacklist.map.kmer.50.1.0.dgv.gsd.sorted.merge.bed.gz
#       — The standard WGS GRCh38 exclusion BED from resources/GRCh38/
#         (generated by generateExcludeBed.sh or downloaded from the repository)
#
# Usage:
#   bash genUKB.exclude.sh
#
# Output:
#   ngs_pca_exclude.sv_blacklist.map.kmer.50.1.0.dgv.gsd.xgen.sorted.merge.bed.gz
#   ngs_pca_exclude.sv_blacklist.map.kmer.50.1.0.dgv.gsd.xgen.sorted.merge.bed.gz.tbi

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Raw xgen capture BED (downloaded from UK Biobank field 3801)
xgen_raw="xgen_plus_spikein.b38.bed"

# Compressed and indexed xgen BED with "chr" prefix added
xgen_chr="xgen_plus_spikein.b38.chr.bed.gz"

# WGS exclusion BED (produced by resources/GRCh38/generateExcludeBed.sh)
wgs_exclude="../ngs_pca_exclude.sv_blacklist.map.kmer.50.1.0.dgv.gsd.sorted.merge.bed.gz"

# Final combined WES exclusion BED
out_bed="ngs_pca_exclude.sv_blacklist.map.kmer.50.1.0.dgv.gsd.xgen.sorted.merge.bed.gz"

# Buffer (bp) added on each side of each exome capture interval
buffer=20000

# ---------------------------------------------------------------------------
# Step 1: Prepare xgen capture BED
#   - Add "chr" prefix to chromosome names
#   - Apply ±20 kb buffer (clamp at 0 for negative start coordinates)
# ---------------------------------------------------------------------------
echo "[1/3] Buffering xgen capture intervals by ${buffer} bp..."
cat "$xgen_raw" \
    | awk -v buf="$buffer" '{
        start = $2 - buf; if (start < 0) start = 0
        print "chr"$1"\t"start"\t"($3 + buf)
      }' \
    | bgzip > "$xgen_chr"

# ---------------------------------------------------------------------------
# Step 2: Merge xgen BED with WGS exclusion BED
# ---------------------------------------------------------------------------
echo "[2/3] Merging with WGS exclusion BED..."
{ zcat "$wgs_exclude"; zcat "$xgen_chr"; } \
    | bedtools sort \
    | bedtools merge \
    | bgzip > "$out_bed"

# ---------------------------------------------------------------------------
# Step 3: Index the output BED with tabix
# ---------------------------------------------------------------------------
echo "[3/3] Indexing with tabix..."
tabix "$out_bed"

echo "Done. Output: ${out_bed}"







