#!/usr/bin/env bash
# =============================================================================
# install_aspera.sh — Build the Aspera image and verify it against ENA
# =============================================================================
#
#   bash install_aspera.sh        # idempotent; safe to re-run
#
# Builds aspera.def into ${WORK_DIR}/aspera/aspera.sif, copies the ENA key out
# of the image, and leaves an 'ascp' wrapper that config.sh picks up. See
# aspera.def for why a current client AND a new key are both required.
#
# Nothing here is mandatory: if the build is not possible, the pipeline falls
# back to parallel HTTPS downloads (USE_ASPERA=0 skips ascp entirely).
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/config.sh"

DEF_FILE="${SCRIPT_DIR}/aspera.def"
# Explicit path: config.sh resolves ASPERA_BIN to the bare string "ascp" until
# this wrapper exists, so using ASPERA_BIN here would write to the CWD.
ASPERA_WRAPPER="${ASPERA_HOME}/bin/ascp"

echo "Aspera provisioning -> ${ASPERA_HOME}"
mkdir -p "${ASPERA_HOME}/bin" "${ASPERA_HOME}/etc"

if [[ -f "${ASPERA_SIF}" ]]; then
  echo "[1/3] Image already built: ${ASPERA_SIF}"
else
  command -v apptainer &>/dev/null || {
    echo "ERROR: apptainer not found. Set USE_ASPERA=0 to use the HTTPS path."
    exit 1
  }
  echo "[1/3] Building ${ASPERA_SIF} (downloads ~68 MB; runs a login test)..."
  # --fakeroot is needed to build from a definition file as a normal user.
  if ! apptainer build --fakeroot "${ASPERA_SIF}" "${DEF_FILE}"; then
    rm -f "${ASPERA_SIF}"
    echo
    echo "ERROR: build failed. The usual cause is that this site does not permit"
    echo "'apptainer build --fakeroot'. The pipeline does not need Aspera:"
    echo "  USE_ASPERA=0 bash 01_download_and_mosdepth.sh"
    exit 1
  fi
fi

# 01_download_and_mosdepth.sh passes '-i <host path>', so the key has to exist
# on the host too; WORK_DIR is bind-mounted into the container at run time.
echo "[2/3] Extracting the ENA key to ${ASPERA_SSH_KEY}"
apptainer exec "${ASPERA_SIF}" cat /opt/aspera/etc/ebi_public.key > "${ASPERA_SSH_KEY}"
chmod 600 "${ASPERA_SSH_KEY}"

cat > "${ASPERA_WRAPPER}" <<EOF
#!/usr/bin/env bash
# Generated by install_aspera.sh
exec apptainer exec --bind "${WORK_DIR}" "${ASPERA_SIF}" ascp "\$@"
EOF
chmod +x "${ASPERA_WRAPPER}"

echo "[3/3] Verifying login against ENA..."
if "${ASPERA_WRAPPER}" -L- -P "${ASPERA_PORT}" --mode=test-login \
     -i "${ASPERA_SSH_KEY}" "${ENA_ASPERA_USER}" 2>&1 | grep -q "test login succeeded"; then
  echo "SUCCESS — Aspera is ready; the pipeline will use it automatically."
else
  echo "FAILED — could not authenticate to ENA."
  echo "If EBI rotated the key, rebuild: rm -f ${ASPERA_SIF} && bash install_aspera.sh"
  exit 1
fi
